ТЗ10: Доработка RestAPI: Friends и Likes
NullDave/java-filmorate pull request #5
Opened 2023-04-17 21:20 UTC by NullDave

2023-04-18 15:16 UTC, ErkinKasymaliev requested changes
привет, очень хорошая работа!
оставил пару комментов

2023-04-18 15:16 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorHandler.java
> +public class ErrorHandler {
лучше переименуйте в ExceptionHandler

2023-04-18 15:16 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/exception/error/ValidationException.java
> +package ru.yandex.practicum.filmorate.exception.error;
это пакет не нужен

2023-04-18 15:16 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/exception/Errors.java
> +public class Errors {
этот класс не нужен, просто просто где надо бросайте исключение, например,
return new NotFoundException(String.format("Не удалось найти фильм с id =%d", id));

2023-04-18 15:16 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (!films.containsKey(id)) return Optional.empty();
просто сделайте так:
Film film = films.get(id);
return film != null ? Optional.of(film) : Optional.empty();

2023-04-18 15:16 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (!films.containsKey(film.getId())) throw Errors.notFoundFilm(film.getId());
просто return new NotFoundException(String.format("Не удалось найти фильм с id =%d", id));

2023-04-18 15:16 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +public class InMemoryUserStorage implements UserStorage {
смотрите комменты в InMemoryFilmStorage

2023-04-18 15:16 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.isEmpty()) throw Errors.notFoundFilm(id);
return new NotFoundException(...);

2023-04-18 15:34 UTC, NullDave commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorHandler.java
> +public class ErrorHandler {
а можно назвать его ExceptionApiHandler?

2023-04-18 16:09 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorHandler.java
> +public class ErrorHandler {
лучше так ExceptionHandler)

2023-04-18 16:19 UTC, NullDave commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorHandler.java
> +public class ErrorHandler {
просто ExceptionHandler это аннотация которую мы используем, если мы назовем класс ExceptionHandler в котором я использую эту аннотацию будит выглядит так. И по мне это несильно прагматично.
![image](https://user-images.githubusercontent.com/90875835/232840396-8bb2b112-34e6-4755-a058-af3a4611458b.png)

2023-04-18 16:24 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorHandler.java
> +public class ErrorHandler {
*ударил в грязь лицом*
ExceptionApiHandler - пойдет)

2023-04-19 03:52 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-05-02 18:54 UTC, merged